### ISSUE TITLE
过滤菜品列表

### ISSUE THREAD

**Issue by ttionya** [xyqfer/youpin#12]
可以过滤低于1元的菜品以及评分低于阈值的菜品

低于1元的基本都是调料之类的，评分低的就不推荐了

**Comment by ttionya** [comment]
也可以选择推荐人气的前几名

**Comment by xyqfer** [comment]
- 已过滤4分以下的商品
- 价格是与规格绑定的，不好做过滤

**Comment by xyqfer** [comment]
menu v2 接口已过滤
